// =====================================================================
// annotate-levels.js — generate level-meta.js from the difficulty scorer.
//
// The game cannot run BFS on device (state spaces reach 10^5–10^6 nodes), so
// per-level metadata that depends on it is precomputed here and shipped as a
// tiny data file:
//   tier  — difficulty tier by composite score (never by move count)
//   score — composite difficulty 0–100
//   cog   — germane cognitive load 0–100
//   hint  — the first three moves of one optimal solution ({from, to})
//
// Run `npm run annotate` after editing levels.js. A test asserts the file is
// in sync with the declared optimalMoves so a stale file cannot ship.
// =====================================================================
const fs = require('fs');
const path = require('path');
const vm = require('vm');
const { analyzeAll } = require('./difficulty.js');

const root = path.resolve(__dirname, '..');
function loadScript(file, suffix) {
  const source = fs.readFileSync(path.join(root, file), 'utf8');
  const context = { window: {} };
  vm.createContext(context);
  return vm.runInContext(source + suffix, context, { filename: file });
}
const WORLDS = loadScript('levels.js', '; WORLDS;');
const SERIAL = loadScript('serial.js', '; window.SERIAL;');
const { bfs } = require('./difficulty.js');

const rows = analyzeAll(WORLDS);
const meta = {};
for (const r of rows) {
  if (!r.f) continue;
  const wid = String(r.worldId);
  if (!meta[wid]) meta[wid] = {};
  meta[wid][String(r.level - 1)] = {
    opt: r.f.moves,
    score: Number(r.score.toFixed(1)),
    cog: Number(r.cogLoad.toFixed(1)),
    tier: r.tier.id,
    hint: r.f.hint.map(m => [m.from, m.to])
  };
}

// Weekly serial episodes: full optimal solutions for the "previously on" replay.
meta.serial = {};
for (const season of SERIAL.SERIAL_SEASONS) {
  meta.serial[season.id] = {};
  season.episodes.forEach((ep, i) => {
    const r = bfs(ep.level);
    if (!r) throw new Error(`serial ${season.id} episode ${i + 1} is unsolvable`);
    meta.serial[season.id][String(i)] = { opt: r.optimalMoves, solution: r.moves.map(m => [m.from, m.to]) };
  });
}

const banner = `// GENERATED by scripts/annotate-levels.js — do not edit by hand.
// Per-level difficulty metadata (tier by composite score, opening hint).
// Regenerate with: npm run annotate
`;
const body = `const LEVEL_META = ${JSON.stringify(meta)};\n` +
  `if (typeof module !== 'undefined' && module.exports) module.exports = LEVEL_META;\n`;
fs.writeFileSync(path.join(root, 'level-meta.js'), banner + body);
const count = Object.entries(meta).filter(([k]) => k !== 'serial').reduce((s, [, w]) => s + Object.keys(w).length, 0);
const episodes = Object.values(meta.serial).reduce((s, w) => s + Object.keys(w).length, 0);
console.log(`level-meta.js written: ${count} levels annotated, ${episodes} serial episodes`);
